import Head from 'next/head';
import { FC } from 'react';

import FadeInOutContainer from '@/components/animated/FadeInOutContainer';
import Explore from '@/components/pages/HomePage/Explore';
import FAQ from '@/components/pages/HomePage/FAQ';
import FindCandidate from '@/components/pages/HomePage/FindCandidate';
import FindToday from '@/components/pages/HomePage/FindToday';
import FindWork from '@/components/pages/HomePage/FindWork';
import Matchminds from '@/components/pages/HomePage/Matchminds';
import { ErrorData } from '@/components/ui/Error';
import { getHomePageData } from '@/services/HomePageService';

import styles from './styles.module.scss';

const Home: FC = async () => {
  const { data, status } = await getHomePageData();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        {status && data ? (
          <FadeInOutContainer key="home">
            <Matchminds
              content={data.mainPageCallToActionBlocks || []}
              text={data.mainPageHeaders[0]}
            />
            <Explore
              content={data.mainPageFeatures || []}
              text={data.mainPageFeaturesBlocks[0] || null}
            />
            <FindCandidate
              text={data.mainPageCandidateBlocks[0] || null}
              content={data.candidateBlockItems || []}
            />
            <FindWork
              text={data.mainPageCompanyBlocks[0] || null}
              content={data.companyBlockItems || []}
            />
            <FAQ text={data.mainPageFaqBlocks[0] || null} content={data.faqItems || []} />
            <FindToday text={data.mainPageCallToActionFooters[0] || null} />
          </FadeInOutContainer>
        ) : (
          <ErrorData />
        )}
      </div>
    </>
  );
};

export default Home;
